export const TYPES = {
    READ_STATE: "READ_STATE",
    AGREGAR_A_CARRITO: "AGREGAR_A_CARRITO",
    ELIMINAR_UNIDAD: "ELIMINAR_UNIDAD",
    ELIMINAR_TODOS: "ELIMINAR_TODOS",
    LIMPIAR_CARRITO: "LIMPIAR_CARRITO"
}